package fr.divalto.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 *
 */
@WebService(name = "DivaltoServiceSoap", targetNamespace = "http://www.Divalto.fr/WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DivaltoServiceSoap {

    /**
     *
     * @param webServiceDivaResult
     * @param retour
     * @param param
     * @param action
     */
    @WebMethod(operationName = "WebServiceDiva", action = "http://www.Divalto.fr/WebService/WebServiceDiva")
    @RequestWrapper(localName = "WebServiceDiva", targetNamespace = "http://www.Divalto.fr/WebService/", className = "fr.divalto.webservice.WebServiceDiva")
    @ResponseWrapper(localName = "WebServiceDivaResponse", targetNamespace = "http://www.Divalto.fr/WebService/", className = "fr.divalto.webservice.WebServiceDivaResponse")
    public void webServiceDiva(
            @WebParam(name = "action", targetNamespace = "http://www.Divalto.fr/WebService/") String action,
            @WebParam(name = "param", targetNamespace = "http://www.Divalto.fr/WebService/") String param,
            @WebParam(name = "WebServiceDivaResult", targetNamespace = "http://www.Divalto.fr/WebService/", mode = WebParam.Mode.OUT) Holder<Integer> webServiceDivaResult,
            @WebParam(name = "retour", targetNamespace = "http://www.Divalto.fr/WebService/", mode = WebParam.Mode.OUT) Holder<String> retour);

}
