package fr.divalto.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "DivaltoService", targetNamespace = "http://www.Divalto.fr/WebService/", wsdlLocation = "http://upsit.tgcc.ma:82/webservicediva.asmx?wsdl")
public class DivaltoService
        extends Service {

    private final static URL DIVALTOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.divalto.webservice.DivaltoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.divalto.webservice.DivaltoService.class.getResource(".");
            //  url = new URL(baseUrl, "http://upsit.tgcc.ma:82/webservicediva.asmx?wsdl");
                url = new URL(baseUrl, "http://192.168.0.202:81/WebServiceDiva.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://upsit.tgcc.ma:82/webservicediva.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DIVALTOSERVICE_WSDL_LOCATION = url;
    }

    public DivaltoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DivaltoService() {
        super(DIVALTOSERVICE_WSDL_LOCATION, new QName("http://www.Divalto.fr/WebService/", "DivaltoService"));
    }

    /**
     *
     * @return returns DivaltoServiceSoap
     */
    @WebEndpoint(name = "DivaltoServiceSoap")
    public DivaltoServiceSoap getDivaltoServiceSoap() {
        return super.getPort(new QName("http://www.Divalto.fr/WebService/", "DivaltoServiceSoap"), DivaltoServiceSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns DivaltoServiceSoap
     */
    @WebEndpoint(name = "DivaltoServiceSoap")
    public DivaltoServiceSoap getDivaltoServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.Divalto.fr/WebService/", "DivaltoServiceSoap"), DivaltoServiceSoap.class, features);
    }

}
